language: ruby
rvm:
  - 1.9.3
env:
  - DB=sqlite3
  - DB=mysql
  - DB=postgresql
script:
  - RAILS_ENV=test spec
before_script:
  - mysql -e 'create database myapp_test'
  - psql -c 'create database myapp_test' -U postgres
  - rake db:migrate
  - rake db:test:prepare