language: ruby
rvm:
  - "1.9.3"
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-19mode
before_script:
  - psql -c 'create database myapp_test;' -U postgres
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
