mysql: &mysql
  adapter: mysql2
  username: root
  password:
  database: myapp_<%= Rails.env %><%= ENV['TEST_ENV_NUMBER'] %>

postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: myapp_<%= Rails.env %><%= ENV['TEST_ENV_NUMBER'] %>
  min_messages: ERROR

sqlite: &sqlite
  adapter: sqlite3
  database: db/myapp_<%= Rails.env %><%= ENV['TEST_ENV_NUMBER'] %>.sqlite3

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "postgresql" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
