require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EnhancementsController do

  # This should return the minimal set of attributes required to create a valid
  # Enhancement. As you add validations to Enhancement, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EnhancementsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all enhancements as @enhancements" do
      enhancement = Enhancement.create! valid_attributes
      get :index, {}, valid_session
      assigns(:enhancements).should eq([enhancement])
    end
  end

  describe "GET show" do
    it "assigns the requested enhancement as @enhancement" do
      enhancement = Enhancement.create! valid_attributes
      get :show, {:id => enhancement.to_param}, valid_session
      assigns(:enhancement).should eq(enhancement)
    end
  end

  describe "GET new" do
    it "assigns a new enhancement as @enhancement" do
      get :new, {}, valid_session
      assigns(:enhancement).should be_a_new(Enhancement)
    end
  end

  describe "GET edit" do
    it "assigns the requested enhancement as @enhancement" do
      enhancement = Enhancement.create! valid_attributes
      get :edit, {:id => enhancement.to_param}, valid_session
      assigns(:enhancement).should eq(enhancement)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Enhancement" do
        expect {
          post :create, {:enhancement => valid_attributes}, valid_session
        }.to change(Enhancement, :count).by(1)
      end

      it "assigns a newly created enhancement as @enhancement" do
        post :create, {:enhancement => valid_attributes}, valid_session
        assigns(:enhancement).should be_a(Enhancement)
        assigns(:enhancement).should be_persisted
      end

      it "redirects to the created enhancement" do
        post :create, {:enhancement => valid_attributes}, valid_session
        response.should redirect_to(Enhancement.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved enhancement as @enhancement" do
        # Trigger the behavior that occurs when invalid params are submitted
        Enhancement.any_instance.stub(:save).and_return(false)
        post :create, {:enhancement => {}}, valid_session
        assigns(:enhancement).should be_a_new(Enhancement)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Enhancement.any_instance.stub(:save).and_return(false)
        post :create, {:enhancement => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested enhancement" do
        enhancement = Enhancement.create! valid_attributes
        # Assuming there are no other enhancements in the database, this
        # specifies that the Enhancement created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Enhancement.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => enhancement.to_param, :enhancement => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested enhancement as @enhancement" do
        enhancement = Enhancement.create! valid_attributes
        put :update, {:id => enhancement.to_param, :enhancement => valid_attributes}, valid_session
        assigns(:enhancement).should eq(enhancement)
      end

      it "redirects to the enhancement" do
        enhancement = Enhancement.create! valid_attributes
        put :update, {:id => enhancement.to_param, :enhancement => valid_attributes}, valid_session
        response.should redirect_to(enhancement)
      end
    end

    describe "with invalid params" do
      it "assigns the enhancement as @enhancement" do
        enhancement = Enhancement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Enhancement.any_instance.stub(:save).and_return(false)
        put :update, {:id => enhancement.to_param, :enhancement => {}}, valid_session
        assigns(:enhancement).should eq(enhancement)
      end

      it "re-renders the 'edit' template" do
        enhancement = Enhancement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Enhancement.any_instance.stub(:save).and_return(false)
        put :update, {:id => enhancement.to_param, :enhancement => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested enhancement" do
      enhancement = Enhancement.create! valid_attributes
      expect {
        delete :destroy, {:id => enhancement.to_param}, valid_session
      }.to change(Enhancement, :count).by(-1)
    end

    it "redirects to the enhancements list" do
      enhancement = Enhancement.create! valid_attributes
      delete :destroy, {:id => enhancement.to_param}, valid_session
      response.should redirect_to(enhancements_url)
    end
  end

end
