require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe JewelriesController do
  let(:attack_power_enhancement) { Enhancement.find_by_name('Power') }
  let(:amulet) { create(:trinket, :amulet, enhancement: attack_power_enhancement) }
  let(:ring) { create(:trinket, :ring, enhancement: attack_power_enhancement) }
  let(:accessory) { create(:trinket, :accessory, enhancement: attack_power_enhancement) }

  # This should return the minimal set of attributes required to create a valid
  # Jewelry. As you add validations to Jewelry, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
      trinkets: [
        { id: amulet.id },
        { id: ring.id },
        { id: accessory.id }
      ]
    }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JewelriesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all jewelries as @jewelries" do
      jewelry = create(:jewelry)
      get :index, {}, valid_session
      assigns(:jewelries).should eq([jewelry])
    end
  end

  describe "GET show" do
    it "assigns the requested jewelry as @jewelry" do
      jewelry = create(:jewelry)
      get :show, {:id => jewelry.to_param}, valid_session
      assigns(:jewelry).should eq(jewelry)
    end
  end

  describe "GET new" do
    it "assigns a new jewelry as @jewelry" do
      get :new, {}, valid_session
      assigns(:jewelry).should be_a_new(Jewelry)
    end
  end

  describe "GET edit" do
    it "assigns the requested jewelry as @jewelry" do
      jewelry = create(:jewelry)
      get :edit, {:id => jewelry.to_param}, valid_session
      assigns(:jewelry).should eq(jewelry)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Jewelry" do
        expect {
          post :create, {:jewelry => valid_attributes}, valid_session
        }.to change(Jewelry, :count).by(1)
      end

      it "assigns a newly created jewelry as @jewelry" do
        post :create, {:jewelry => valid_attributes}, valid_session
        assigns(:jewelry).should be_a(Jewelry)
        assigns(:jewelry).should be_persisted
      end

      it "redirects to the created jewelry" do
        post :create, {:jewelry => valid_attributes}, valid_session
        response.should redirect_to(jewelry_url(Jewelry.last))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved jewelry as @jewelry" do
        # Trigger the behavior that occurs when invalid params are submitted
        Jewelry.any_instance.stub(:save).and_return(false)
        post :create, {:jewelry => {}}, valid_session
        assigns(:jewelry).should be_a_new(Jewelry)
      end

      it "redirects to the 'jewelries#index' action" do
        # Trigger the behavior that occurs when invalid params are submitted
        Jewelry.any_instance.stub(:save).and_return(false)
        post :create, {:jewelry => {}}, valid_session
        response.should redirect_to(controller: :jewelries, action: :index)
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested jewelry" do
        jewelry = create(:jewelry)
        # Assuming there are no other jewelries in the database, this
        # specifies that the Jewelry created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Jewelry.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => jewelry.to_param, :jewelry => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested jewelry as @jewelry" do
        jewelry = create(:jewelry)
        put :update, {:id => jewelry.to_param, :jewelry => valid_attributes}, valid_session
        # Have to add 3 attack power because stats get regenerated
        jewelry.attack_power = jewelry.attack_power + 3
        
        assigns(:jewelry).should eq(jewelry)
      end

      it "redirects to the jewelry" do
        jewelry = create(:jewelry)
        put :update, {:id => jewelry.to_param, :jewelry => valid_attributes}, valid_session
        response.should redirect_to(jewelry_url(jewelry))
      end
    end

    describe "with invalid params" do
      it "assigns the jewelry as @jewelry" do
        jewelry = create(:jewelry)
        # Trigger the behavior that occurs when invalid params are submitted
        Jewelry.any_instance.stub(:save).and_return(false)
        put :update, {:id => jewelry.to_param, :jewelry => {}}, valid_session
        assigns(:jewelry).should eq(jewelry)
      end

      it "redirects to the 'jewelries#show' action" do
        jewelry = create(:jewelry)
        # Trigger the behavior that occurs when invalid params are submitted
        Jewelry.any_instance.stub(:save).and_return(false)
        put :update, {:id => jewelry.to_param, :jewelry => {}}, valid_session
        response.should redirect_to(jewelry_url(jewelry))
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested jewelry" do
      jewelry = create(:jewelry)
      expect {
        delete :destroy, {:id => jewelry.to_param}, valid_session
      }.to change(Jewelry, :count).by(-1)
    end

    it "redirects to the jewelries list" do
      jewelry = create(:jewelry)
      delete :destroy, {:id => jewelry.to_param}, valid_session
      response.should redirect_to(jewelries_url)
    end
  end

end
